### ISSUE TITLE
Market Feature

### ISSUE THREAD

**Issue by Bitcoinera** [e-money/lunie-light#11]
Market Feature Milestone.

@mdyring feel free to edit

- [x] 1: support market-related transactions in PageTransactions #1 
- [x] 2: add active orders, current prices to the market page
- [x] 3: add basic view and ActionModal for orders (basic functionality)
- [x] 4: support blacklisting of tokens #43 
- [ ] 5: Phase 2: add historic data using a subgraph (explore this option) #28

**Comment by Bitcoinera** [comment]
We can close this after merging #29 and then move onto #27

**Comment by Bitcoinera** [comment]
I think we can close this one and continue with Phase 2
